package com.mobilehub.model;

import java.io.Serializable;
import java.sql.Timestamp; // To match TIMESTAMP type in your database

public class Product implements Serializable {
    private static final long serialVersionUID = 3L; // Consistent or updated based on changes

    private int id;
    private String name;
    private String description;
    private double price;
    private String category;
    private int stockQuantity;
    private String imageUrl;    // This will store the full data: URL string or relative path
    private Timestamp createdAt; // Matches 'createdAt' TIMESTAMP in your 'products' table
    private Timestamp updatedAt; // Matches 'updatedAt' TIMESTAMP in your 'products' table

    // Default constructor
    public Product() {
    }

    // Constructor used when creating a NEW product (ID is auto-generated by DB, timestamps usually too)
    public Product(String name, String description, double price, String category, int stockQuantity, String imageUrl) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.stockQuantity = stockQuantity;
        this.imageUrl = imageUrl;
        // createdAt and updatedAt are typically set by the database or DAO on insert/update
    }

    // Full constructor, often used when retrieving a product from the database
    public Product(int id, String name, String description, double price, String category, int stockQuantity, String imageUrl, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.stockQuantity = stockQuantity;
        this.imageUrl = imageUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    // --- Getters ---
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public double getPrice() {
        return price;
    }

    public String getCategory() {
        return category;
    }

    public int getStockQuantity() {
        return stockQuantity;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    // --- Setters ---
    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "Product{" +
               "id=" + id +
               ", name='" + name + '\'' +
               ", price=" + price +
               ", category='" + category + '\'' +
               ", stockQuantity=" + stockQuantity +
               ", imageUrl='" + (imageUrl != null && imageUrl.length() > 30 ? imageUrl.substring(0, 30) + "..." : imageUrl) + '\'' + // Truncate long data URLs for logging
               ", createdAt=" + createdAt +
               ", updatedAt=" + updatedAt +
               '}';
    }
}