package com.mobilehub.model;

import java.io.Serializable;
import java.sql.Timestamp; // For created_at, updated_at

public class Product implements Serializable {
    private static final long serialVersionUID = 3L; // Example

    private int id;
    private String name;
    private String description;
    private double price;
    private String category; // e.g., "Smartphone", "Accessory"
    private int stockQuantity;
    private String imageUrl;    // URL or path to the product image
    private Timestamp createdAt;
    private Timestamp updatedAt;

    // Default constructor
    public Product(int i, String string, String string2, String string3, double d) {}

    // Constructor for creating new products (ID is auto-generated by DB)
    public Product(String name, String description, double price, String category, int stockQuantity, String imageUrl) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.stockQuantity = stockQuantity;
        this.imageUrl = imageUrl;
    }

    // Full constructor (when retrieving from DB)
    public Product(int id, String name, String description, double price, String category, int stockQuantity, String imageUrl, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.stockQuantity = stockQuantity;
        this.imageUrl = imageUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Product() {
		// TODO Auto-generated constructor stub
	}

	// Getters
    public int getId() { return id; }
    public String getName() { return name; }
    public String getDescription() { return description; }
    public double getPrice() { return price; }
    public String getCategory() { return category; }
    public int getStockQuantity() { return stockQuantity; }
    public String getImageUrl() { return imageUrl; }
    public Timestamp getCreatedAt() { return createdAt; }
    public Timestamp getUpdatedAt() { return updatedAt; }

    // Setters
    public void setId(int id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setDescription(String description) { this.description = description; }
    public void setPrice(double price) { this.price = price; }
    public void setCategory(String category) { this.category = category; }
    public void setStockQuantity(int stockQuantity) { this.stockQuantity = stockQuantity; }
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }
    public void setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }

    @Override
    public String toString() {
        return "Product{" + "id=" + id + ", name='" + name + '\'' + ", price=" + price + ", stockQuantity=" + stockQuantity + '}';
    }
}