/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mobilehub.view;

import com.mobilehub.controller.algorithms.BinarySearch;
import com.mobilehub.controller.algorithms.InsertionSort;
import com.mobilehub.controller.algorithms.MergeSort;
import com.mobilehub.controller.algorithms.SelectionSort;
import com.mobilehub.model.ModelDetails;
import com.mobilehub.util.Validation;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aayush
 */
public class login extends javax.swing.JFrame {
    private List<ModelDetails> modelList;
    private int phoneCount; // To store the count

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        initializeData();
        homepage.setVisible(false);
        adminpage.setVisible(false);
        salespage.setVisible(false);
        productpage.setVisible(false);
        navigation.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        login = new javax.swing.JPanel();
        logintext = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usertext = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        loginbutton = new javax.swing.JToggleButton();
        passtext = new javax.swing.JPasswordField();
        loginimage = new javax.swing.JLabel();
        passworderror = new javax.swing.JLabel();
        usernameerror = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        navigation = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        product = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        homepage = new javax.swing.JPanel();
        logoutbutton = new javax.swing.JButton();
        welcomeback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        homepageimagelabel = new javax.swing.JLabel();
        adminpage = new javax.swing.JPanel();
        admintitle = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        modelid = new javax.swing.JLabel();
        modelfield = new javax.swing.JTextField();
        brand = new javax.swing.JLabel();
        modelname = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        brandfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        quantityfield = new javax.swing.JTextField();
        storage = new javax.swing.JLabel();
        storagefield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        admintable = new javax.swing.JTable();
        searchtext = new javax.swing.JTextField();
        insertionradio = new javax.swing.JRadioButton();
        selectionradio = new javax.swing.JRadioButton();
        mergeradio = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        salespage = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        productpage = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setMaximumSize(new java.awt.Dimension(1000, 600));
        login.setMinimumSize(new java.awt.Dimension(1000, 600));
        login.setPreferredSize(new java.awt.Dimension(1000, 600));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        logintext.setForeground(new java.awt.Color(102, 102, 102));
        logintext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logintext.setText("LOGIN");
        login.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 200, 70));

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setText("Username");
        username.setPreferredSize(new java.awt.Dimension(70, 30));
        login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 90, 40));
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 155, 37, -1));

        usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextActionPerformed(evt);
            }
        });
        login.add(usertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 190, 40));

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("Password");
        login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 90, -1));

        loginbutton.setBackground(new java.awt.Color(205, 59, 88));
        loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("Login");
        loginbutton.setActionCommand("LOGIN");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        login.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 160, 40));

        passtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtextActionPerformed(evt);
            }
        });
        login.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 190, 40));

        loginimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/logo 1 (1).png"))); // NOI18N
        login.add(loginimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        passworderror.setForeground(new java.awt.Color(51, 102, 255));
        login.add(passworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 190, 20));

        usernameerror.setForeground(new java.awt.Color(51, 102, 255));
        login.add(usernameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 190, 20));

        mainpanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        mainpanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        mainpanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation.setBackground(new java.awt.Color(204, 204, 255));

        logo.setBackground(new java.awt.Color(204, 204, 255));
        logo.setOpaque(true);

        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product.setText("Products");
        product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productMouseClicked(evt);
            }
        });

        sales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales.setText("Sales");
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
        });

        admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setText("Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navigationLayout = new javax.swing.GroupLayout(navigation);
        navigation.setLayout(navigationLayout);
        navigationLayout.setHorizontalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navigationLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        navigationLayout.setVerticalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(24, 24, 24)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        mainpanel.add(navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 500));

        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        homepage.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 50));

        welcomeback.setBackground(new java.awt.Color(204, 204, 255));
        welcomeback.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeback.setForeground(new java.awt.Color(51, 0, 102));
        welcomeback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeback.setText("Welcome Back !!!");
        welcomeback.setOpaque(true);
        homepage.add(welcomeback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Phones");
        homepage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 30));
        homepage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Brands");
        homepage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Apple, Samsung, Oppo, OnePlus, Pixel");
        homepage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 390, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View Products");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        homepage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Add Products");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        homepage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 180, 110));

        homepageimagelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepageimagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/homepage.jpg"))); // NOI18N
        homepage.add(homepageimagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 870, 500));

        mainpanel.add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 0, 860, 600));

        adminpage.setBackground(new java.awt.Color(255, 255, 255));
        adminpage.setMaximumSize(new java.awt.Dimension(850, 600));
        adminpage.setMinimumSize(new java.awt.Dimension(850, 600));
        adminpage.setPreferredSize(new java.awt.Dimension(850, 600));
        adminpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admintitle.setBackground(new java.awt.Color(204, 204, 255));
        admintitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        admintitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admintitle.setText("AdminPage");
        admintitle.setOpaque(true);
        adminpage.add(admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        adminpage.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, 37));

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        adminpage.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 100, 37));

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        adminpage.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 100, 37));

        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        adminpage.add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 100, 37));

        modelid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelid.setText("Model Id");
        adminpage.add(modelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 489, 66, 24));

        modelfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelfieldActionPerformed(evt);
            }
        });
        adminpage.add(modelfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 75, -1));

        brand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand.setText("Brand");
        adminpage.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 45, -1));

        modelname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelname.setText("Model Name");
        adminpage.add(modelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price.setText("Price");
        adminpage.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 493, -1, -1));

        quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantity.setText("Quantity");
        adminpage.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));
        adminpage.add(brandfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 75, -1));
        adminpage.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 111, -1));
        adminpage.add(pricefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 74, -1));

        quantityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityfieldActionPerformed(evt);
            }
        });
        adminpage.add(quantityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 74, -1));

        storage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storage.setText("Storage");
        adminpage.add(storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        storagefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storagefieldActionPerformed(evt);
            }
        });
        adminpage.add(storagefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 77, -1));

        searchbutton.setText("Search");
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
        });
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        adminpage.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 100, 37));

        admintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Id", "Model Name", "Brand", "Price", "Storage", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(admintable);
        if (admintable.getColumnModel().getColumnCount() > 0) {
            admintable.getColumnModel().getColumn(0).setResizable(false);
            admintable.getColumnModel().getColumn(1).setResizable(false);
            admintable.getColumnModel().getColumn(2).setResizable(false);
            admintable.getColumnModel().getColumn(3).setResizable(false);
            admintable.getColumnModel().getColumn(4).setResizable(false);
            admintable.getColumnModel().getColumn(5).setResizable(false);
        }

        adminpage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 760, 290));
        adminpage.add(searchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 100, 30));

        buttonGroup1.add(insertionradio);
        insertionradio.setText("Insertion Sort [ Model ID ]");
        insertionradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertionradioActionPerformed(evt);
            }
        });
        adminpage.add(insertionradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        buttonGroup1.add(selectionradio);
        selectionradio.setText("Selection Sort [ Price ]");
        selectionradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionradioActionPerformed(evt);
            }
        });
        adminpage.add(selectionradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        buttonGroup1.add(mergeradio);
        mergeradio.setText("Merge Sort [ Quantity ]");
        mergeradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeradioActionPerformed(evt);
            }
        });
        adminpage.add(mergeradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        jLabel20.setText("Search By Brand");
        adminpage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        mainpanel.add(adminpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 600));

        salespage.setMaximumSize(new java.awt.Dimension(850, 600));
        salespage.setMinimumSize(new java.awt.Dimension(850, 600));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/samsung.jpg"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sales Page");
        jLabel15.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Best Selling");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("In-Demand");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/pixel.jpg"))); // NOI18N

        javax.swing.GroupLayout salespageLayout = new javax.swing.GroupLayout(salespage);
        salespage.setLayout(salespageLayout);
        salespageLayout.setHorizontalGroup(
            salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salespageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salespageLayout.setVerticalGroup(
            salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salespageLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salespageLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(salespageLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(salespageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salespageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salespageLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainpanel.add(salespage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 600));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Product Page");
        jLabel8.setOpaque(true);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/apple.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/oneplus.jpg"))); // NOI18N
        jLabel10.setOpaque(true);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/pixel.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/samsung.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/oppo.png"))); // NOI18N

        javax.swing.GroupLayout productpageLayout = new javax.swing.GroupLayout(productpage);
        productpage.setLayout(productpageLayout);
        productpageLayout.setHorizontalGroup(
            productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productpageLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productpageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productpageLayout.setVerticalGroup(
            productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpageLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productpageLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(productpageLayout.createSequentialGroup()
                        .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(productpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 600));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilehub/resources/image.jpg"))); // NOI18N
        mainpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        
        // Retrieve the input username and password
        String username = usertext.getText();
        String password = new String(passtext.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) { 
            usernameerror.setText("Username and Password cannot be EMPTY!!");
        } 
        // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) { 
            passworderror.setText("Username or Password is INCORRECT!!");
            
        } 
        // If all conditions are met, proceed to load the main screen
        else {
             usernameerror.setText(""); // Clear any previous error messages
             passworderror.setText(""); // Clear any previous error messages
            login.setVisible(false);
            mainpanel.setVisible(true);
            navigation.setVisible(true);

            homepage.setVisible(true);
            adminpage.setVisible(false);
            salespage.setVisible(false);
            productpage.setVisible(false);
        }
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void usertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextActionPerformed

    private void passtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtextActionPerformed

    private void quantityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityfieldActionPerformed

    private void modelfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelfieldActionPerformed

    private void storagefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storagefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storagefieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        homepage.setVisible(true);
        adminpage.setVisible(false);
        salespage.setVisible(false);
        productpage.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMouseClicked
        // TODO add your handling code here:
        homepage.setVisible(false);
        adminpage.setVisible(false);
        salespage.setVisible(false);
        productpage.setVisible(true);
    }//GEN-LAST:event_productMouseClicked

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        // TODO add your handling code here:
        homepage.setVisible(false);
        adminpage.setVisible(false);
        salespage.setVisible(true);
        productpage.setVisible(false);
    }//GEN-LAST:event_salesMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        homepage.setVisible(false);
        adminpage.setVisible(true);
        salespage.setVisible(false);
        productpage.setVisible(false);
    }//GEN-LAST:event_adminMouseClicked

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        homepage.setVisible(false);
        adminpage.setVisible(false);
        salespage.setVisible(false);
        productpage.setVisible(false);
        navigation.setVisible(false);
        
        
        
        usertext.setText("");
                
        passtext.setText("");
        
        login.setVisible(true);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
            homepage.setVisible(false);
            adminpage.setVisible(false);
            salespage.setVisible(false);
            productpage.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            homepage.setVisible(false);
            adminpage.setVisible(true);
            salespage.setVisible(false);
            productpage.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        // Get text from each input field
        String modelIdText = modelfield.getText().trim();
        String modelName = namefield.getText().trim();
        String brand = brandfield.getText().trim();
        String priceText = pricefield.getText().trim();
        String storage = storagefield.getText().trim();
        String quantityText = quantityfield.getText().trim();

        // Validations
        if (!Validation.isNotNullOrEmpty(modelIdText, "Model ID", this) ||
            !Validation.isNotNullOrEmpty(modelName, "Model Name", this) ||
            !Validation.isNotNullOrEmpty(brand, "Brand", this) ||
            !Validation.isNotNullOrEmpty(priceText, "Price", this) ||
            !Validation.isNotNullOrEmpty(storage, "Storage", this) ||
            !Validation.isNotNullOrEmpty(quantityText, "Quantity", this)) {
            return; // Stop if any required field is empty
        }

        if (!Validation.isValidInteger(modelIdText, "Model ID", this) ||
            !Validation.isValidInteger(priceText, "Price", this) ||
            !Validation.isValidInteger(quantityText, "Quantity", this)) {
            return; // Stop if any field is not an integer
        }

        int modelId = Integer.parseInt(modelIdText);
        int price = Integer.parseInt(priceText);
        int quantity = Integer.parseInt(quantityText);

         if (!Validation.isPositive(modelId, "Model ID", this) ||
                !Validation.isPositive(price, "Price", this) ||
                !Validation.isPositive(quantity, "Quantity", this)) {
            return;
        }


        // Create a new ModelDetails object
        ModelDetails newModel = new ModelDetails(modelId, modelName, brand, price, storage, quantity);

        //Add to admin table
         addMobile(newModel);


        // Clear input fields after successful add
        modelfield.setText("");
        namefield.setText("");
        brandfield.setText("");
        pricefield.setText("");
        storagefield.setText("");
        quantityfield.setText("");

        JOptionPane.showMessageDialog(this, "Model added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addbuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
                int selectedRow = admintable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

       // Get text from each input field
        String modelIdText = modelfield.getText().trim();
        String modelName = namefield.getText().trim();
        String brand = brandfield.getText().trim();
        String priceText = pricefield.getText().trim();
        String storage = storagefield.getText().trim();
        String quantityText = quantityfield.getText().trim();
        
         // Validations
        if (!Validation.isNotNullOrEmpty(modelIdText, "Model ID", this) ||
            !Validation.isNotNullOrEmpty(modelName, "Model Name", this) ||
            !Validation.isNotNullOrEmpty(brand, "Brand", this) ||
            !Validation.isNotNullOrEmpty(priceText, "Price", this) ||
            !Validation.isNotNullOrEmpty(storage, "Storage", this) ||
            !Validation.isNotNullOrEmpty(quantityText, "Quantity", this)) {
            return; // Stop if any required field is empty
        }

        if (!Validation.isValidInteger(modelIdText, "Model ID", this) ||
            !Validation.isValidInteger(priceText, "Price", this) ||
            !Validation.isValidInteger(quantityText, "Quantity", this)) {
            return; // Stop if any field is not an integer
        }

        int modelId = Integer.parseInt(modelIdText);
        int price = Integer.parseInt(priceText);
        int quantity = Integer.parseInt(quantityText);

        if (!Validation.isPositive(modelId, "Model ID", this) ||
                !Validation.isPositive(price, "Price", this) ||
                !Validation.isPositive(quantity, "Quantity", this)) {
            return;
        }


        // Create a new ModelDetails object
        ModelDetails updatedModel = new ModelDetails(modelId, modelName, brand, price, storage, quantity);

       // Update the model list
        modelList.set(selectedRow, updatedModel);


        //Update the table
        DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();

         tableModel.setValueAt(updatedModel.getModelId(),selectedRow,0);
        tableModel.setValueAt(updatedModel.getModelName(),selectedRow,1);
        tableModel.setValueAt(updatedModel.getBrand(),selectedRow,2);
        tableModel.setValueAt(updatedModel.getPrice(),selectedRow,3);
        tableModel.setValueAt(updatedModel.getStorage(),selectedRow,4);
        tableModel.setValueAt(updatedModel.getQuantity(),selectedRow,5);


        // Clear input fields
       modelfield.setText("");
        namefield.setText("");
        brandfield.setText("");
        pricefield.setText("");
        storagefield.setText("");
        quantityfield.setText("");


        JOptionPane.showMessageDialog(this, "Model updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        String modelIdText = modelfield.getText().trim();


        // Validate model ID
        if (!Validation.isNotNullOrEmpty(modelIdText, "Model ID", this) ||
            !Validation.isValidInteger(modelIdText, "Model ID", this))
            {
                return;
            }

        int modelId = Integer.parseInt(modelIdText);

        if (!Validation.isPositive(modelId, "Model ID", this))
        {
            return;
        }

        // Search for model in list
        int indexToDelete = -1;
        for (int i = 0; i < modelList.size(); i++) {
            if (modelList.get(i).getModelId() == modelId) {
                indexToDelete = i;
                break;
            }
        }
        // If found delete it from the table and model list
        if (indexToDelete != -1) {
             // Remove from the table model first
             DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();
             tableModel.removeRow(indexToDelete);

            // Remove from the model list.
            modelList.remove(indexToDelete);

          // clear the input field
           modelfield.setText("");

            JOptionPane.showMessageDialog(this, "Model deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
          JOptionPane.showMessageDialog(this, "Model with ID: " + modelId + " not found.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
        String searchText = searchtext.getText().trim();

        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a brand name to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Sort the modelList by brand name (required for binary search)
        BinarySearch.sortByBrand(modelList);

        // Perform binary search for the brand name
        int index = BinarySearch.searchByBrand(modelList, searchText);

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Brand not found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Update the table with the search result
            DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();
            BinarySearch.updateTableWithSearchResult(modelList, tableModel, searchText);
        }
    }//GEN-LAST:event_searchbuttonMouseClicked

    private void selectionradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionradioActionPerformed
        // TODO add your handling code here:
       // Get the table model
        DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();

        // Perform selection sort on the modelList based on price
        SelectionSort.sortByPrice(modelList, tableModel);
    }//GEN-LAST:event_selectionradioActionPerformed

    private void mergeradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeradioActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();

        // Perform merge sort on the modelList based on quantity
        MergeSort.sortByQuantity(modelList, tableModel);
    }//GEN-LAST:event_mergeradioActionPerformed

    private void insertionradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertionradioActionPerformed
        // TODO add your handling code here:
            DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();

    // Perform insertion sort on the modelList based on modelId
    InsertionSort.sortByModelId(modelList, tableModel);
    }//GEN-LAST:event_insertionradioActionPerformed

    private void initializeData() {
        modelList = new LinkedList<>();
        phoneCount = 0; // Initialize count to 0

    // Adding sample mobiles
        addMobile(new ModelDetails(1,"Samsung Galaxy S23", "Samsung", 900, "256GB", 10));
        addMobile(new ModelDetails(2,"iPhone 15 Pro", "Apple", 1200, "512GB", 5));
        addMobile(new ModelDetails(3,"Google Pixel 8", "Google", 800, "128GB", 3));
        addMobile(new ModelDetails(4,"Google Pixel 7", "Google", 800, "128GB", 3));
        addMobile(new ModelDetails(5,"Google Pixel 3", "Google", 800, "128GB", 3));

    }
    
    private void addMobile(ModelDetails model) {
    modelList.add(model);
    phoneCount++; //increment the row count
    jLabel2.setText(String.valueOf(phoneCount));
    DefaultTableModel tableModel = (DefaultTableModel) admintable.getModel();
    tableModel.addRow(new Object[]{
            model.getModelId(), model.getModelName(), model.getBrand(),model.getPrice(), model.getStorage(), model.getQuantity()
    });
    
    // **Add this line to notify the table that a new row has been added:**
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel admin;
    private javax.swing.JPanel adminpage;
    private javax.swing.JTable admintable;
    private javax.swing.JLabel admintitle;
    private javax.swing.JLabel brand;
    private javax.swing.JTextField brandfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel homepageimagelabel;
    private javax.swing.JRadioButton insertionradio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel login;
    private javax.swing.JToggleButton loginbutton;
    private javax.swing.JLabel loginimage;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JRadioButton mergeradio;
    private javax.swing.JTextField modelfield;
    private javax.swing.JLabel modelid;
    private javax.swing.JLabel modelname;
    private javax.swing.JTextField namefield;
    private javax.swing.JPanel navigation;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passworderror;
    private javax.swing.JLabel price;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel product;
    private javax.swing.JPanel productpage;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JLabel sales;
    private javax.swing.JPanel salespage;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchtext;
    private javax.swing.JRadioButton selectionradio;
    private javax.swing.JLabel storage;
    private javax.swing.JTextField storagefield;
    private javax.swing.JButton updatebutton;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usernameerror;
    private javax.swing.JTextField usertext;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables
}
